/*
 jQuery JavaScript Library v3.0.0
 https://jquery.com/

 Includes Sizzle.js
 https://sizzlejs.com/

 Copyright jQuery Foundation and other contributors
 Released under the MIT license
 https://jquery.org/license

 Date: 2016-06-09T18:02Z
 Sizzle CSS Selector Engine v2.3.0
 https://sizzlejs.com/

 Copyright jQuery Foundation and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2016-01-04
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(m){var p=0;return function(){return p<m.length?{done:!1,value:m[p++]}:{done:!0}}};$jscomp.arrayIterator=function(m){return{next:$jscomp.arrayIteratorImpl(m)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(m,p,r){if(m==Array.prototype||m==Object.prototype)return m;m[p]=r.value;return m};$jscomp.getGlobal=function(m){m=["object"==typeof globalThis&&globalThis,m,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var p=0;p<m.length;++p){var r=m[p];if(r&&r.Math==Math)return r}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(m,p){var r=$jscomp.propertyToPolyfillSymbol[p];if(null==r)return m[p];r=m[r];return void 0!==r?r:m[p]};
$jscomp.polyfill=function(m,p,r,t){p&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(m,p,r,t):$jscomp.polyfillUnisolated(m,p,r,t))};$jscomp.polyfillUnisolated=function(m,p,r,t){r=$jscomp.global;m=m.split(".");for(t=0;t<m.length-1;t++){var w=m[t];w in r||(r[w]={});r=r[w]}m=m[m.length-1];t=r[m];p=p(t);p!=t&&null!=p&&$jscomp.defineProperty(r,m,{configurable:!0,writable:!0,value:p})};
$jscomp.polyfillIsolated=function(m,p,r,t){var w=m.split(".");m=1===w.length;t=w[0];t=!m&&t in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var ja=0;ja<w.length-1;ja++){var W=w[ja];W in t||(t[W]={});t=t[W]}w=w[w.length-1];r=$jscomp.IS_SYMBOL_NATIVE&&"es6"===r?t[w]:null;p=p(r);null!=p&&(m?$jscomp.defineProperty($jscomp.polyfills,w,{configurable:!0,writable:!0,value:p}):p!==r&&($jscomp.propertyToPolyfillSymbol[w]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(w):$jscomp.POLYFILL_PREFIX+w,
w=$jscomp.propertyToPolyfillSymbol[w],$jscomp.defineProperty(t,w,{configurable:!0,writable:!0,value:p})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(m){if(m)return m;var p=function(m,p){this.$jscomp$symbol$id_=m;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:p})};p.prototype.toString=function(){return this.$jscomp$symbol$id_};var r=0,t=function(m){if(this instanceof t)throw new TypeError("Symbol is not a constructor");return new p("jscomp_symbol_"+(m||"")+"_"+r++,m)};return t},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(m){if(m)return m;m=Symbol("Symbol.iterator");for(var p="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),r=0;r<p.length;r++){var t=$jscomp.global[p[r]];"function"===typeof t&&"function"!=typeof t.prototype[m]&&$jscomp.defineProperty(t.prototype,m,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return m},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(m){m={next:m};m[Symbol.iterator]=function(){return this};return m};
(function(m,p){"object"===typeof module&&"object"===typeof module.exports?module.exports=m.document?p(m,!0):function(m){if(!m.document)throw Error("jQuery requires a window with a document");return p(m)}:p(m)})("undefined"!==typeof window?window:this,function(m,p){function r(a,b){b=b||q;var d=b.createElement("script");d.text=a;b.head.appendChild(d).parentNode.removeChild(d)}function t(a){var b=!!a&&"length"in a&&a.length,d=c.type(a);return"function"===d||c.isWindow(a)?!1:"array"===d||0===b||"number"===
typeof b&&0<b&&b-1 in a}function w(a,b,d){if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,a)!==d});if(b.nodeType)return c.grep(a,function(a){return a===b!==d});if("string"===typeof b){if(Pb.test(b))return c.filter(b,a,d);b=c.filter(b,a)}return c.grep(a,function(a){return-1<Aa.call(b,a)!==d&&1===a.nodeType})}function ja(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function W(a){var b={};c.each(a.match(S)||[],function(a,c){b[c]=!0});return b}function ka(a){return a}function la(a){throw a;
}function $a(a,b,d){var e;try{a&&c.isFunction(e=a.promise)?e.call(a).done(b).fail(d):a&&c.isFunction(e=a.then)?e.call(a,b,d):b.call(void 0,a)}catch(f){d.call(void 0,f)}}function ba(){q.removeEventListener("DOMContentLoaded",ba);m.removeEventListener("load",ba);c.ready()}function va(){this.expando=c.expando+va.uid++}function ab(a,b,d){if(void 0===d&&1===a.nodeType)if(d="data-"+b.replace(Qb,"-$&").toLowerCase(),d=a.getAttribute(d),"string"===typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:
+d+""===d?+d:Rb.test(d)?JSON.parse(d):d}catch(e){}J.set(a,b,d)}else d=void 0;return d}function bb(a,b,d,e){var f=1,g=20,h=e?function(){return e.cur()}:function(){return c.css(a,b,"")},l=h(),k=d&&d[3]||(c.cssNumber[b]?"":"px"),n=(c.cssNumber[b]||"px"!==k&&+l)&&ca.exec(c.css(a,b));if(n&&n[3]!==k){k=k||n[3];d=d||[];n=+l||1;do f=f||".5",n/=f,c.style(a,b,n+k);while(f!==(f=h()/l)&&1!==f&&--g)}if(d){n=+n||+l||0;var m=d[1]?n+(d[1]+1)*d[2]:+d[2];e&&(e.unit=k,e.start=n,e.end=m)}return m}function ma(a,b){for(var d,
e,f=[],g=0,h=a.length;g<h;g++)if(e=a[g],e.style)if(d=e.style.display,b){if("none"===d&&(f[g]=x.get(e,"display")||null,f[g]||(e.style.display="")),""===e.style.display&&wa(e)){d=g;var l=e.ownerDocument;e=e.nodeName;var k=cb[e];k||(l=l.body.appendChild(l.createElement(e)),k=c.css(l,"display"),l.parentNode.removeChild(l),"none"===k&&(k="block"),cb[e]=k);l=k;f[d]=l}}else"none"!==d&&(f[g]="none",x.set(e,"display",d));for(g=0;g<h;g++)null!=f[g]&&(a[g].style.display=f[g]);return a}function F(a,b){var d=
"undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&c.nodeName(a,b)?c.merge([a],d):d}function Oa(a,b){for(var d=0,c=a.length;d<c;d++)x.set(a[d],"globalEval",!b||x.get(b[d],"globalEval"))}function db(a,b,d,e,f){for(var g,h,l,k=b.createDocumentFragment(),n=[],m=0,A=a.length;m<A;m++)if((g=a[m])||0===g)if("object"===c.type(g))c.merge(n,g.nodeType?[g]:g);else if(Sb.test(g)){h=h||k.appendChild(b.createElement("div"));
l=(eb.exec(g)||["",""])[1].toLowerCase();l=O[l]||O._default;h.innerHTML=l[1]+c.htmlPrefilter(g)+l[2];for(l=l[0];l--;)h=h.lastChild;c.merge(n,h.childNodes);h=k.firstChild;h.textContent=""}else n.push(b.createTextNode(g));k.textContent="";for(m=0;g=n[m++];)if(e&&-1<c.inArray(g,e))f&&f.push(g);else if(a=c.contains(g.ownerDocument,g),h=F(k.appendChild(g),"script"),a&&Oa(h),d)for(l=0;g=h[l++];)fb.test(g.type||"")&&d.push(g);return k}function Ba(){return!0}function na(){return!1}function gb(){try{return q.activeElement}catch(a){}}
function Pa(a,b,d,e,f,g){var h;if("object"===typeof b){"string"!==typeof d&&(e=e||d,d=void 0);for(h in b)Pa(a,h,d,e,b[h],g);return a}null==e&&null==f?(f=d,e=d=void 0):null==f&&("string"===typeof d?(f=e,e=void 0):(f=e,e=d,d=void 0));if(!1===f)f=na;else if(!f)return a;if(1===g){var l=f;f=function(a){c().off(a);return l.apply(this,arguments)};f.guid=l.guid||(l.guid=c.guid++)}return a.each(function(){c.event.add(this,b,f,e,d)})}function hb(a,b){return c.nodeName(a,"table")&&c.nodeName(11!==b.nodeType?
b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a:a}function Tb(a){a.type=(null!==a.getAttribute("type"))+"/"+a.type;return a}function Ub(a){var b=Vb.exec(a.type);b?a.type=b[1]:a.removeAttribute("type");return a}function ib(a,b){var d;if(1===b.nodeType){if(x.hasData(a)){var e=x.access(a);var f=x.set(b,e);if(e=e.events)for(g in delete f.handle,f.events={},e)for(f=0,d=e[g].length;f<d;f++)c.event.add(b,g,e[g][f])}if(J.hasData(a)){var g=J.access(a);g=c.extend({},g);J.set(b,g)}}}function oa(a,
b,d,e){b=jb.apply([],b);var f,g=0,h=a.length,l=h-1,k=b[0],n=c.isFunction(k);if(n||1<h&&"string"===typeof k&&!z.checkClone&&Wb.test(k))return a.each(function(c){var f=a.eq(c);n&&(b[0]=k.call(this,c,f.html()));oa(f,b,d,e)});if(h){var m=db(b,a[0].ownerDocument,!1,a,e);var A=m.firstChild;1===m.childNodes.length&&(m=A);if(A||e){A=c.map(F(m,"script"),Tb);for(f=A.length;g<h;g++){var v=m;g!==l&&(v=c.clone(v,!0,!0),f&&c.merge(A,F(v,"script")));d.call(a[g],v,g)}if(f)for(m=A[A.length-1].ownerDocument,c.map(A,
Ub),g=0;g<f;g++)v=A[g],fb.test(v.type||"")&&!x.access(v,"globalEval")&&c.contains(m,v)&&(v.src?c._evalUrl&&c._evalUrl(v.src):r(v.textContent.replace(Xb,""),m))}}return a}function kb(a,b,d){for(var e=b?c.filter(b,a):a,f=0;null!=(b=e[f]);f++)d||1!==b.nodeType||c.cleanData(F(b)),b.parentNode&&(d&&c.contains(b.ownerDocument,b)&&Oa(F(b,"script")),b.parentNode.removeChild(b));return a}function pa(a,b,d){var e=a.style;if(d=d||Fa(a)){var f=d.getPropertyValue(b)||d[b];""!==f||c.contains(a.ownerDocument,a)||
(f=c.style(a,b));if(!z.pixelMarginRight()&&Qa.test(f)&&lb.test(b)){a=e.width;b=e.minWidth;var g=e.maxWidth;e.minWidth=e.maxWidth=e.width=f;f=d.width;e.width=a;e.minWidth=b;e.maxWidth=g}}return void 0!==f?f+"":f}function mb(a,b){return{get:function(){if(a())delete this.get;else return(this.get=b).apply(this,arguments)}}}function nb(a){if(a in ob)return a;for(var b=a[0].toUpperCase()+a.slice(1),d=pb.length;d--;)if(a=pb[d]+b,a in ob)return a}function qb(a,b,d){return(a=ca.exec(b))?Math.max(0,a[2]-(d||
0))+(a[3]||"px"):b}function rb(a,b,d,e,f){b=d===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===d&&(g+=c.css(a,d+da[b],!0,f)),e?("content"===d&&(g-=c.css(a,"padding"+da[b],!0,f)),"margin"!==d&&(g-=c.css(a,"border"+da[b]+"Width",!0,f))):(g+=c.css(a,"padding"+da[b],!0,f),"padding"!==d&&(g+=c.css(a,"border"+da[b]+"Width",!0,f)));return g}function sb(a,b,d){var e,f=!0,g=Fa(a),h="border-box"===c.css(a,"boxSizing",!1,g);a.getClientRects().length&&(e=a.getBoundingClientRect()[b]);
if(0>=e||null==e){e=pa(a,b,g);if(0>e||null==e)e=a.style[b];if(Qa.test(e))return e;f=h&&(z.boxSizingReliable()||e===a.style[b]);e=parseFloat(e)||0}return e+rb(a,b,d||(h?"border":"content"),f,g)+"px"}function G(a,b,d,c,f){return new G.prototype.init(a,b,d,c,f)}function tb(){X&&(m.requestAnimationFrame(tb),c.fx.tick())}function ub(){m.setTimeout(function(){qa=void 0});return qa=c.now()}function Ga(a,b){var d=0,c={height:a};for(b=b?1:0;4>d;d+=2-b){var f=da[d];c["margin"+f]=c["padding"+f]=a}b&&(c.opacity=
c.width=a);return c}function vb(a,b,d){for(var c,f=(H.tweeners[b]||[]).concat(H.tweeners["*"]),g=0,h=f.length;g<h;g++)if(c=f[g].call(d,b,a))return c}function Yb(a,b){var d,e;for(d in a){var f=c.camelCase(d);var g=b[f];var h=a[d];c.isArray(h)&&(g=h[1],h=a[d]=h[0]);d!==f&&(a[f]=h,delete a[d]);if((e=c.cssHooks[f])&&"expand"in e)for(d in h=e.expand(h),delete a[f],h)d in a||(a[d]=h[d],b[d]=g);else b[f]=g}}function H(a,b,d){var e,f=0,g=H.prefilters.length,h=c.Deferred().always(function(){delete l.elem}),
l=function(){if(e)return!1;var b=qa||ub();b=Math.max(0,k.startTime+k.duration-b);for(var d=1-(b/k.duration||0),c=0,f=k.tweens.length;c<f;c++)k.tweens[c].run(d);h.notifyWith(a,[k,d,b]);if(1>d&&f)return b;h.resolveWith(a,[k]);return!1},k=h.promise({elem:a,props:c.extend({},b),opts:c.extend(!0,{specialEasing:{},easing:c.easing._default},d),originalProperties:b,originalOptions:d,startTime:qa||ub(),duration:d.duration,tweens:[],createTween:function(b,d){var e=c.Tween(a,k.opts,b,d,k.opts.specialEasing[b]||
k.opts.easing);k.tweens.push(e);return e},stop:function(b){var d=0,c=b?k.tweens.length:0;if(e)return this;for(e=!0;d<c;d++)k.tweens[d].run(1);b?(h.notifyWith(a,[k,1,0]),h.resolveWith(a,[k,b])):h.rejectWith(a,[k,b]);return this}});d=k.props;for(Yb(d,k.opts.specialEasing);f<g;f++)if(b=H.prefilters[f].call(k,a,d,k.opts))return c.isFunction(b.stop)&&(c._queueHooks(k.elem,k.opts.queue).stop=c.proxy(b.stop,b)),b;c.map(d,vb,k);c.isFunction(k.opts.start)&&k.opts.start.call(a,k);c.fx.timer(c.extend(l,{elem:a,
anim:k,queue:k.opts.queue}));return k.progress(k.opts.progress).done(k.opts.done,k.opts.complete).fail(k.opts.fail).always(k.opts.always)}function aa(a){return a.getAttribute&&a.getAttribute("class")||""}function Ra(a,b,d,e){var f;if(c.isArray(b))c.each(b,function(b,c){d||Zb.test(a)?e(a,c):Ra(a+"["+("object"===typeof c&&null!=c?b:"")+"]",c,d,e)});else if(d||"object"!==c.type(b))e(a,b);else for(f in b)Ra(a+"["+f+"]",b[f],d,e)}function wb(a){return function(b,d){"string"!==typeof b&&(d=b,b="*");var e,
f=0,g=b.toLowerCase().match(S)||[];if(c.isFunction(d))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(d)):(a[e]=a[e]||[]).push(d)}}function xb(a,b,d,e){function f(l){var k;g[l]=!0;c.each(a[l]||[],function(a,c){var l=c(b,d,e);if("string"===typeof l&&!h&&!g[l])return b.dataTypes.unshift(l),f(l),!1;if(h)return!(k=l)});return k}var g={},h=a===Sa;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Ta(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(d in b)void 0!==b[d]&&((f[d]?a:e||
(e={}))[d]=b[d]);e&&c.extend(!0,a,e);return a}function yb(a){return c.isWindow(a)?a:9===a.nodeType&&a.defaultView}var N=[],q=m.document,$b=Object.getPrototypeOf,ea=N.slice,jb=N.concat,Ua=N.push,Aa=N.indexOf,Ha={},zb=Ha.toString,Ia=Ha.hasOwnProperty,Ab=Ia.toString,ac=Ab.call(Object),z={},c=function(a,b){return new c.fn.init(a,b)},bc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,cc=/^-ms-/,dc=/-([a-z])/g,ec=function(a,b){return b.toUpperCase()};c.fn=c.prototype={jquery:"3.0.0",constructor:c,length:0,toArray:function(){return ea.call(this)},
get:function(a){return null!=a?0>a?this[a+this.length]:this[a]:ea.call(this)},pushStack:function(a){a=c.merge(this.constructor(),a);a.prevObject=this;return a},each:function(a){return c.each(this,a)},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},slice:function(){return this.pushStack(ea.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&
a<b?[this[a]]:[])},end:function(){return this.prevObject||this.constructor()},push:Ua,sort:N.sort,splice:N.splice};c.extend=c.fn.extend=function(){var a,b,d,e=arguments[0]||{},f=1,g=arguments.length,h=!1;"boolean"===typeof e&&(h=e,e=arguments[f]||{},f++);"object"===typeof e||c.isFunction(e)||(e={});f===g&&(e=this,f--);for(;f<g;f++)if(null!=(a=arguments[f]))for(b in a){var l=e[b];var k=a[b];e!==k&&(h&&k&&(c.isPlainObject(k)||(d=c.isArray(k)))?(d?(d=!1,l=l&&c.isArray(l)?l:[]):l=l&&c.isPlainObject(l)?
l:{},e[b]=c.extend(h,l,k)):void 0!==k&&(e[b]=k))}return e};c.extend({expando:"jQuery"+("3.0.0"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isFunction:function(a){return"function"===c.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){var b=c.type(a);return("number"===b||"string"===b)&&!isNaN(a-parseFloat(a))},isPlainObject:function(a){if(!a||"[object Object]"!==zb.call(a))return!1;a=$b(a);if(!a)return!0;
a=Ia.call(a,"constructor")&&a.constructor;return"function"===typeof a&&Ab.call(a)===ac},isEmptyObject:function(a){for(var b in a)return!1;return!0},type:function(a){return null==a?a+"":"object"===typeof a||"function"===typeof a?Ha[zb.call(a)]||"object":typeof a},globalEval:function(a){r(a)},camelCase:function(a){return a.replace(cc,"ms-").replace(dc,ec)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b){var d,c=0;if(t(a))for(d=a.length;c<d&&!1!==
b.call(a[c],c,a[c]);c++);else for(c in a)if(!1===b.call(a[c],c,a[c]))break;return a},trim:function(a){return null==a?"":(a+"").replace(bc,"")},makeArray:function(a,b){var d=b||[];null!=a&&(t(Object(a))?c.merge(d,"string"===typeof a?[a]:a):Ua.call(d,a));return d},inArray:function(a,b,d){return null==b?-1:Aa.call(b,a,d)},merge:function(a,b){for(var d=+b.length,c=0,f=a.length;c<d;c++)a[f++]=b[c];a.length=f;return a},grep:function(a,b,d){for(var c=[],f=0,g=a.length,h=!d;f<g;f++)d=!b(a[f],f),d!==h&&c.push(a[f]);
return c},map:function(a,b,c){var d,f=0,g=[];if(t(a))for(d=a.length;f<d;f++){var h=b(a[f],f,c);null!=h&&g.push(h)}else for(f in a)h=b(a[f],f,c),null!=h&&g.push(h);return jb.apply([],g)},guid:1,proxy:function(a,b){if("string"===typeof b){var d=a[b];b=a;a=d}if(c.isFunction(a)){var e=ea.call(arguments,2);d=function(){return a.apply(b||this,e.concat(ea.call(arguments)))};d.guid=a.guid=a.guid||c.guid++;return d}},now:Date.now,support:z});"function"===typeof Symbol&&(c.fn[Symbol.iterator]=N[Symbol.iterator]);
c.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),function(a,b){Ha["[object "+b+"]"]=b.toLowerCase()});var V=function(a){function b(a,b,c,d){var e,f,g,I,h=b&&b.ownerDocument,u=b?b.nodeType:9;c=c||[];if("string"!==typeof a||!a||1!==u&&9!==u&&11!==u)return c;if(!d&&((b?b.ownerDocument||b:T)!==y&&xa(b),b=b||y,Y)){if(11!==u&&(I=va.exec(a)))if(e=I[1])if(9===u)if(f=b.getElementById(e)){if(f.id===e)return c.push(f),c}else return c;else{if(h&&(f=h.getElementById(e))&&
Da(b,f)&&f.id===e)return c.push(f),c}else{if(I[2])return ra.apply(c,b.getElementsByTagName(a)),c;if((e=I[3])&&L.getElementsByClassName&&b.getElementsByClassName)return ra.apply(c,b.getElementsByClassName(e)),c}if(!(!L.qsa||Ka[a+" "]||R&&R.test(a))){if(1!==u){h=b;var l=a}else if("object"!==b.nodeName.toLowerCase()){(g=b.getAttribute("id"))?g=g.replace(pa,ta):b.setAttribute("id",g=D);f=ba(a);for(e=f.length;e--;)f[e]="#"+g+" "+p(f[e]);l=f.join(",");h=ca.test(a)&&A(b.parentNode)||b}if(l)try{return ra.apply(c,
h.querySelectorAll(l)),c}catch(Jc){}finally{g===D&&b.removeAttribute("id")}}}return Ba(a.replace(V,"$1"),b,c,d)}function c(){function a(c,d){b.push(c+" ")>E.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function e(a){a[D]=!0;return a}function f(a){var b=y.createElement("fieldset");try{return!!a(b)}catch(u){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){for(var c=a.split("|"),d=c.length;d--;)E.attrHandle[c[d]]=b}function h(a,b){var c=b&&a,d=c&&1===
a.nodeType&&1===b.nodeType&&a.sourceIndex-b.sourceIndex;if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function l(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function k(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function n(a){return function(b){return"label"in b&&b.disabled===a||"form"in b&&b.disabled===a||"form"in b&&!1===b.disabled&&(b.isDisabled===a||b.isDisabled!==!a&&("label"in b||
!za(b))!==a)}}function m(a){return e(function(b){b=+b;return e(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=c[e]))})})}function A(a){return a&&"undefined"!==typeof a.getElementsByTagName&&a}function v(){}function p(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function Ea(a,b,c){var d=b.dir,e=b.next,f=e||d,g=c&&"parentNode"===f,I=J++;return b.first?function(b,c,e){for(;b=b[d];)if(1===b.nodeType||g)return a(b,c,e)}:function(b,c,h){var u,l=[fa,I];
if(h)for(;b=b[d];){if((1===b.nodeType||g)&&a(b,c,h))return!0}else for(;b=b[d];)if(1===b.nodeType||g){var k=b[D]||(b[D]={});k=k[b.uniqueID]||(k[b.uniqueID]={});if(e&&e===b.nodeName.toLowerCase())b=b[d]||b;else{if((u=k[f])&&u[0]===fa&&u[1]===I)return l[2]=u[2];k[f]=l;if(l[2]=a(b,c,h))return!0}}}}function x(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function r(a,b,c,d,e){for(var f,g=[],I=0,h=a.length,u=null!=b;I<h;I++)if(f=a[I])if(!c||c(f,d,e))g.push(f),
u&&b.push(I);return g}function q(a,c,d,f,g,h){f&&!f[D]&&(f=q(f));g&&!g[D]&&(g=q(g,h));return e(function(e,I,h,u){var l,k=[],n=[],Q=I.length,m;if(!(m=e)){m=c||"*";for(var K=h.nodeType?[h]:h,Ja=[],Ca=0,A=K.length;Ca<A;Ca++)b(m,K[Ca],Ja);m=Ja}m=!a||!e&&c?m:r(m,k,a,h,u);K=d?g||(e?a:Q||f)?[]:I:m;d&&d(m,K,h,u);if(f){var C=r(K,n);f(C,[],h,u);for(h=C.length;h--;)if(l=C[h])K[n[h]]=!(m[n[h]]=l)}if(e){if(g||a){if(g){C=[];for(h=K.length;h--;)(l=K[h])&&C.push(m[h]=l);g(null,K=[],C,u)}for(h=K.length;h--;)(l=K[h])&&
-1<(C=g?N(e,l):k[h])&&(e[C]=!(I[C]=l))}}else K=r(K===I?K.splice(Q,K.length):K),g?g(null,I,K,u):ra.apply(I,K)})}function B(a){var b,c,d=a.length,e=E.relative[a[0].type];var f=e||E.relative[" "];for(var g=e?1:0,h=Ea(function(a){return a===b},f,!0),I=Ea(function(a){return-1<N(b,a)},f,!0),l=[function(a,c,d){a=!e&&(d||c!==w)||((b=c).nodeType?h(a,c,d):I(a,c,d));b=null;return a}];g<d;g++)if(f=E.relative[a[g].type])l=[Ea(x(l),f)];else{f=E.filter[a[g].type].apply(null,a[g].matches);if(f[D]){for(c=++g;c<d&&
!E.relative[a[c].type];c++);return q(1<g&&x(l),1<g&&p(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(V,"$1"),f,g<c&&B(a.slice(g,c)),c<d&&B(a=a.slice(c)),c<d&&p(a))}l.push(f)}return x(l)}function t(a,c){var d=0<c.length,f=0<a.length,g=function(e,g,h,I,l){var u,k,n=0,Q="0",m=e&&[],K=[],C=w,A=e||f&&E.find.TAG("*",l),Ca=fa+=null==C?1:Math.random()||.1,Ja=A.length;for(l&&(w=g===y||g||l);Q!==Ja&&null!=(u=A[Q]);Q++){if(f&&u){var v=0;g||u.ownerDocument===y||(xa(u),h=!Y);for(;k=a[v++];)if(k(u,
g||y,h)){I.push(u);break}l&&(fa=Ca)}d&&((u=!k&&u)&&n--,e&&m.push(u))}n+=Q;if(d&&Q!==n){for(v=0;k=c[v++];)k(m,K,g,h);if(e){if(0<n)for(;Q--;)m[Q]||K[Q]||(K[Q]=Z.call(I));K=r(K)}ra.apply(I,K);l&&!e&&0<K.length&&1<n+c.length&&b.uniqueSort(I)}l&&(fa=Ca,w=C);return m};return d?e(g):g}var z,w,M,P,y,U,Y,R,ya,La,Da,D="sizzle"+1*new Date,T=a.document,fa=0,J=0,F=c(),G=c(),Ka=c(),O=function(a,b){a===b&&(P=!0);return 0},S={}.hasOwnProperty,H=[],Z=H.pop,da=H.push,ra=H.push,aa=H.slice,N=function(a,b){for(var c=
0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},ea=RegExp("[\\x20\\t\\r\\n\\f]+","g"),V=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),ja=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ka=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,ma=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]","g"),na=/:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,
oa=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,X={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:/^\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\]/,PSEUDO:/^:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,
CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},qa=/^(?:input|select|textarea|button)$/i,sa=/^h\d$/i,W=/^[^{]+\{\s*\[native \w/,
va=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ca=/[+~]/,ha=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),ia=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)},pa=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\x80-\uFFFF\w-]/g,ta=function(a,b){return b?"\x00"===a?"\ufffd":a.slice(0,-1)+"\\"+a.charCodeAt(a.length-1).toString(16)+" ":"\\"+a},ua=function(){xa()},za=Ea(function(a){return!0===a.disabled},{dir:"parentNode",
next:"legend"});try{ra.apply(H=aa.call(T.childNodes),T.childNodes),H[T.childNodes.length].nodeType}catch(I){ra={apply:H.length?function(a,b){da.apply(a,aa.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}var L=b.support={};var Aa=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};var xa=b.setDocument=function(a){var b;a=a?a.ownerDocument||a:T;if(a===y||9!==a.nodeType||!a.documentElement)return y;y=a;U=y.documentElement;Y=!Aa(y);
T!==y&&(b=y.defaultView)&&b.top!==b&&(b.addEventListener?b.addEventListener("unload",ua,!1):b.attachEvent&&b.attachEvent("onunload",ua));L.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});L.getElementsByTagName=f(function(a){a.appendChild(y.createComment(""));return!a.getElementsByTagName("*").length});L.getElementsByClassName=W.test(y.getElementsByClassName);L.getById=f(function(a){U.appendChild(a).id=D;return!y.getElementsByName||!y.getElementsByName(D).length});L.getById?
(E.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&Y){var c=b.getElementById(a);return c?[c]:[]}},E.filter.ID=function(a){var b=a.replace(ha,ia);return function(a){return a.getAttribute("id")===b}}):(delete E.find.ID,E.filter.ID=function(a){var b=a.replace(ha,ia);return function(a){return(a="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}});E.find.TAG=L.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a);
if(L.qsa)return b.querySelectorAll(a)}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f};E.find.CLASS=L.getElementsByClassName&&function(a,b){if("undefined"!==typeof b.getElementsByClassName&&Y)return b.getElementsByClassName(a)};ya=[];R=[];if(L.qsa=W.test(y.querySelectorAll))f(function(a){U.appendChild(a).innerHTML="<a id='"+D+"'></a><select id='"+D+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&
R.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||R.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll("[id~="+D+"-]").length||R.push("~=");a.querySelectorAll(":checked").length||R.push(":checked");a.querySelectorAll("a#"+D+"+*").length||R.push(".#.+[+~]")}),f(function(a){a.innerHTML="<a href='' disabled='disabled'></a><select disabled='disabled'><option/></select>";
var b=y.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&R.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");2!==a.querySelectorAll(":enabled").length&&R.push(":enabled",":disabled");U.appendChild(a).disabled=!0;2!==a.querySelectorAll(":disabled").length&&R.push(":enabled",":disabled");a.querySelectorAll("*,:x");R.push(",.*:")});(L.matchesSelector=W.test(La=U.matches||U.webkitMatchesSelector||U.mozMatchesSelector||U.oMatchesSelector||
U.msMatchesSelector))&&f(function(a){L.disconnectedMatch=La.call(a,"*");La.call(a,"[s!='']:x");ya.push("!=",":((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});R=R.length&&new RegExp(R.join("|"));
ya=ya.length&&new RegExp(ya.join("|"));Da=(b=W.test(U.compareDocumentPosition))||W.test(U.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!!(d&&1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};O=b?function(a,b){if(a===b)return P=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;if(c)return c;c=(a.ownerDocument||a)===
(b.ownerDocument||b)?a.compareDocumentPosition(b):1;return c&1||!L.sortDetached&&b.compareDocumentPosition(a)===c?a===y||a.ownerDocument===T&&Da(T,a)?-1:b===y||b.ownerDocument===T&&Da(T,b)?1:M?N(M,a)-N(M,b):0:c&4?-1:1}:function(a,b){if(a===b)return P=!0,0;var c=0;var d=a.parentNode;var e=b.parentNode,f=[a],g=[b];if(!d||!e)return a===y?-1:b===y?1:d?-1:e?1:M?N(M,a)-N(M,b):0;if(d===e)return h(a,b);for(d=a;d=d.parentNode;)f.unshift(d);for(d=b;d=d.parentNode;)g.unshift(d);for(;f[c]===g[c];)c++;return c?
h(f[c],g[c]):f[c]===T?-1:g[c]===T?1:0};return y};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){(a.ownerDocument||a)!==y&&xa(a);c=c.replace(ma,"='$1']");if(!(!L.matchesSelector||!Y||Ka[c+" "]||ya&&ya.test(c)||R&&R.test(c)))try{var d=La.call(a,c);if(d||L.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(K){}return 0<b(c,y,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==y&&xa(a);return Da(a,b)};b.attr=function(a,b){(a.ownerDocument||
a)!==y&&xa(a);var c=E.attrHandle[b.toLowerCase()];c=c&&S.call(E.attrHandle,b.toLowerCase())?c(a,b,!Y):void 0;return void 0!==c?c:L.attributes||!Y?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.escape=function(a){return(a+"").replace(pa,ta)};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;P=!L.detectDuplicates;M=!L.sortStable&&a.slice(0);a.sort(O);if(P){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],
1)}M=null;return a};var la=b.getText=function(a){var b="",c=0;var d=a.nodeType;if(!d)for(;d=a[c++];)b+=la(d);else if(1===d||9===d||11===d){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=la(a)}else if(3===d||4===d)return a.nodeValue;return b};var E=b.selectors={cacheLength:50,createPseudo:e,match:X,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},
preFilter:{ATTR:function(a){a[1]=a[1].replace(ha,ia);a[3]=(a[3]||a[4]||a[5]||"").replace(ha,ia);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(X.CHILD.test(a[0]))return null;a[3]?a[2]=a[4]||a[5]||"":c&&na.test(c)&&(b=ba(c,!0))&&(b=c.indexOf(")",
c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(ha,ia).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=F[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),F(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,
c,d){return function(e){e=b.attr(e,a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(ea," ")+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,l){var k,n;c=f!==g?"nextSibling":
"previousSibling";var m=b.parentNode,I=h&&b.nodeName.toLowerCase();l=!l&&!h;var u=!1;if(m){if(f){for(;c;){for(k=b;k=k[c];)if(h?k.nodeName.toLowerCase()===I:1===k.nodeType)return!1;var Q=c="only"===a&&!Q&&"nextSibling"}return!0}Q=[g?m.firstChild:m.lastChild];if(g&&l){k=m;var C=k[D]||(k[D]={});C=C[k.uniqueID]||(C[k.uniqueID]={});u=C[a]||[];u=(n=u[0]===fa&&u[1])&&u[2];for(k=n&&m.childNodes[n];k=++n&&k&&k[c]||(u=n=0)||Q.pop();)if(1===k.nodeType&&++u&&k===b){C[a]=[fa,n,u];break}}else if(l&&(k=b,C=k[D]||
(k[D]={}),C=C[k.uniqueID]||(C[k.uniqueID]={}),u=C[a]||[],u=n=u[0]===fa&&u[1]),!1===u)for(;(k=++n&&k&&k[c]||(u=n=0)||Q.pop())&&((h?k.nodeName.toLowerCase()!==I:1!==k.nodeType)||!++u||(l&&(C=k[D]||(k[D]={}),C=C[k.uniqueID]||(C[k.uniqueID]={}),C[a]=[fa,u]),k!==b)););u-=e;return u===d||0===u%d&&0<=u/d}}},PSEUDO:function(a,c){var d=E.pseudos[a]||E.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);if(d[D])return d(c);if(1<d.length){var f=[a,a,"",c];return E.setFilters.hasOwnProperty(a.toLowerCase())?
e(function(a,b){for(var e,f=d(a,c),g=f.length;g--;)e=N(a,f[g]),a[e]=!(b[e]=f[g])}):function(a){return d(a,0,f)}}return d}},pseudos:{not:e(function(a){var b=[],c=[],d=wa(a.replace(V,"$1"));return d[D]?e(function(a,b,c,e){e=d(a,null,e,[]);for(var f=a.length;f--;)if(c=e[f])a[f]=!(b[f]=c)}):function(a,e,f){b[0]=a;d(b,null,f,c);b[0]=null;return!c.pop()}}),has:e(function(a){return function(c){return 0<b(a,c).length}}),contains:e(function(a){a=a.replace(ha,ia);return function(b){return-1<(b.textContent||
b.innerText||la(b)).indexOf(a)}}),lang:e(function(a){oa.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(ha,ia).toLowerCase();return function(b){var c;do if(c=Y?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===U},focus:function(a){return a===y.activeElement&&(!y.hasFocus||
y.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:n(!1),disabled:n(!0),checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!E.pseudos.empty(a)},header:function(a){return sa.test(a.nodeName)},input:function(a){return qa.test(a.nodeName)},
button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:m(function(){return[0]}),last:m(function(a,b){return[b-1]}),eq:m(function(a,b,c){return[0>c?c+b:c]}),even:m(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:m(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:m(function(a,b,c){for(b=
0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:m(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};E.pseudos.nth=E.pseudos.eq;for(z in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})E.pseudos[z]=l(z);for(z in{submit:!0,reset:!0})E.pseudos[z]=k(z);v.prototype=E.filters=E.pseudos;E.setFilters=new v;var ba=b.tokenize=function(a,c){var d,e,f,g,h;if(g=G[a+" "])return c?0:g.slice(0);g=a;var l=[];for(h=E.preFilter;g;){if(!k||(d=ja.exec(g)))d&&(g=g.slice(d[0].length)||g),l.push(e=[]);var k=!1;
if(d=ka.exec(g))k=d.shift(),e.push({value:k,type:d[0].replace(V," ")}),g=g.slice(k.length);for(f in E.filter)!(d=X[f].exec(g))||h[f]&&!(d=h[f](d))||(k=d.shift(),e.push({value:k,type:f,matches:d}),g=g.slice(k.length));if(!k)break}return c?g.length:g?b.error(a):G(a,l).slice(0)};var wa=b.compile=function(a,b){var c,d=[],e=[],f=Ka[a+" "];if(!f){b||(b=ba(a));for(c=b.length;c--;)f=B(b[c]),f[D]?d.push(f):e.push(f);f=Ka(a,t(e,d));f.selector=a}return f};var Ba=b.select=function(a,b,c,d){var e,f,g,h="function"===
typeof a&&a,k=!d&&ba(a=h.selector||a);c=c||[];if(1===k.length){var l=k[0]=k[0].slice(0);if(2<l.length&&"ID"===(f=l[0]).type&&L.getById&&9===b.nodeType&&Y&&E.relative[l[1].type]){b=(E.find.ID(f.matches[0].replace(ha,ia),b)||[])[0];if(!b)return c;h&&(b=b.parentNode);a=a.slice(l.shift().value.length)}for(e=X.needsContext.test(a)?0:l.length;e--;){f=l[e];if(E.relative[g=f.type])break;if(g=E.find[g])if(d=g(f.matches[0].replace(ha,ia),ca.test(l[0].type)&&A(b.parentNode)||b)){l.splice(e,1);a=d.length&&p(l);
if(!a)return ra.apply(c,d),c;break}}}(h||wa(a,k))(d,b,!Y,c,!b||ca.test(a)&&A(b.parentNode)||b);return c};L.sortStable=D.split("").sort(O).join("")===D;L.detectDuplicates=!!P;xa();L.sortDetached=f(function(a){return a.compareDocumentPosition(y.createElement("fieldset"))&1});f(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});L.attributes&&f(function(a){a.innerHTML=
"<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});return b}(m);
c.find=V;c.expr=V.selectors;c.expr[":"]=c.expr.pseudos;c.uniqueSort=c.unique=V.uniqueSort;c.text=V.getText;c.isXMLDoc=V.isXML;c.contains=V.contains;c.escapeSelector=V.escape;var sa=function(a,b,d){for(var e=[],f=void 0!==d;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&c(a).is(d))break;e.push(a)}return e},Bb=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},Cb=c.expr.match.needsContext,Db=/^<([a-z][^\/\0>:\x20\t\r\n\f]*)[\x20\t\r\n\f]*\/?>(?:<\/\1>|)$/i,Pb=
/^.[^:#\[\.,]*$/;c.filter=function(a,b,d){var e=b[0];d&&(a=":not("+a+")");return 1===b.length&&1===e.nodeType?c.find.matchesSelector(e,a)?[e]:[]:c.find.matches(a,c.grep(b,function(a){return 1===a.nodeType}))};c.fn.extend({find:function(a){var b,d=this.length,e=this;if("string"!==typeof a)return this.pushStack(c(a).filter(function(){for(b=0;b<d;b++)if(c.contains(e[b],this))return!0}));var f=this.pushStack([]);for(b=0;b<d;b++)c.find(a,e[b],f);return 1<d?c.uniqueSort(f):f},filter:function(a){return this.pushStack(w(this,
a||[],!1))},not:function(a){return this.pushStack(w(this,a||[],!0))},is:function(a){return!!w(this,"string"===typeof a&&Cb.test(a)?c(a):a||[],!1).length}});var gc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]+))$/;(c.fn.init=function(a,b,d){if(!a)return this;d=d||hc;if("string"===typeof a){var e="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:gc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||d).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof c?b[0]:b,c.merge(this,c.parseHTML(e[1],b&&
b.nodeType?b.ownerDocument||b:q,!0)),Db.test(e[1])&&c.isPlainObject(b))for(e in b)if(c.isFunction(this[e]))this[e](b[e]);else this.attr(e,b[e])}else if(a=q.getElementById(e[2]))this[0]=a,this.length=1;return this}return a.nodeType?(this[0]=a,this.length=1,this):c.isFunction(a)?void 0!==d.ready?d.ready(a):a(c):c.makeArray(a,this)}).prototype=c.fn;var hc=c(q);var ic=/^(?:parents|prev(?:Until|All))/,jc={children:!0,contents:!0,next:!0,prev:!0};c.fn.extend({has:function(a){var b=c(a,this),d=b.length;
return this.filter(function(){for(var a=0;a<d;a++)if(c.contains(this,b[a]))return!0})},closest:function(a,b){var d,e=0,f=this.length,g=[],h="string"!==typeof a&&c(a);if(!Cb.test(a))for(;e<f;e++)for(d=this[e];d&&d!==b;d=d.parentNode)if(11>d.nodeType&&(h?-1<h.index(d):1===d.nodeType&&c.find.matchesSelector(d,a))){g.push(d);break}return this.pushStack(1<g.length?c.uniqueSort(g):g)},index:function(a){return a?"string"===typeof a?Aa.call(c(a),this[0]):Aa.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?
this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(c.uniqueSort(c.merge(this.get(),c(a,b))))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return sa(a,"parentNode")},parentsUntil:function(a,b,c){return sa(a,"parentNode",c)},next:function(a){return ja(a,"nextSibling")},prev:function(a){return ja(a,"previousSibling")},nextAll:function(a){return sa(a,
"nextSibling")},prevAll:function(a){return sa(a,"previousSibling")},nextUntil:function(a,b,c){return sa(a,"nextSibling",c)},prevUntil:function(a,b,c){return sa(a,"previousSibling",c)},siblings:function(a){return Bb((a.parentNode||{}).firstChild,a)},children:function(a){return Bb(a.firstChild)},contents:function(a){return a.contentDocument||c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);"Until"!==a.slice(-5)&&(e=d);e&&"string"===typeof e&&(f=c.filter(e,f));1<this.length&&
(jc[a]||c.uniqueSort(f),ic.test(a)&&f.reverse());return this.pushStack(f)}});var S=/\S+/g;c.Callbacks=function(a){a="string"===typeof a?W(a):c.extend({},a);var b,d,e,f,g=[],h=[],l=-1,k=function(){f=a.once;for(e=b=!0;h.length;l=-1)for(d=h.shift();++l<g.length;)!1===g[l].apply(d[0],d[1])&&a.stopOnFalse&&(l=g.length,d=!1);a.memory||(d=!1);b=!1;f&&(g=d?[]:"")},n={add:function(){g&&(d&&!b&&(l=g.length-1,h.push(d)),function v(b){c.each(b,function(b,d){c.isFunction(d)?a.unique&&n.has(d)||g.push(d):d&&d.length&&
"string"!==c.type(d)&&v(d)})}(arguments),d&&!b&&k());return this},remove:function(){c.each(arguments,function(a,b){for(var d;-1<(d=c.inArray(b,g,d));)g.splice(d,1),d<=l&&l--});return this},has:function(a){return a?-1<c.inArray(a,g):0<g.length},empty:function(){g&&(g=[]);return this},disable:function(){f=h=[];g=d="";return this},disabled:function(){return!g},lock:function(){f=h=[];d||b||(g=d="");return this},locked:function(){return!!f},fireWith:function(a,c){f||(c=c||[],c=[a,c.slice?c.slice():c],
h.push(c),b||k());return this},fire:function(){n.fireWith(this,arguments);return this},fired:function(){return!!e}};return n};c.extend({Deferred:function(a){var b=[["notify","progress",c.Callbacks("memory"),c.Callbacks("memory"),2],["resolve","done",c.Callbacks("once memory"),c.Callbacks("once memory"),0,"resolved"],["reject","fail",c.Callbacks("once memory"),c.Callbacks("once memory"),1,"rejected"]],d="pending",e={state:function(){return d},always:function(){f.done(arguments).fail(arguments);return this},
"catch":function(a){return e.then(null,a)},pipe:function(){var a=arguments;return c.Deferred(function(d){c.each(b,function(b,e){var g=c.isFunction(a[e[4]])&&a[e[4]];f[e[1]](function(){var a=g&&g.apply(this,arguments);if(a&&c.isFunction(a.promise))a.promise().progress(d.notify).done(d.resolve).fail(d.reject);else d[e[0]+"With"](this,g?[a]:arguments)})});a=null}).promise()},then:function(a,d,e){function f(a,b,d,e){return function(){var h=this,l=arguments,k=function(){if(!(a<g)){var k=d.apply(h,l);if(k===
b.promise())throw new TypeError("Thenable self-resolution");var n=k&&("object"===typeof k||"function"===typeof k)&&k.then;c.isFunction(n)?e?n.call(k,f(g,b,ka,e),f(g,b,la,e)):(g++,n.call(k,f(g,b,ka,e),f(g,b,la,e),f(g,b,ka,b.notifyWith))):(d!==ka&&(h=void 0,l=[k]),(e||b.resolveWith)(h,l))}},n=e?k:function(){try{k()}catch(B){c.Deferred.exceptionHook&&c.Deferred.exceptionHook(B,n.stackTrace),a+1>=g&&(d!==la&&(h=void 0,l=[B]),b.rejectWith(h,l))}};a?n():(c.Deferred.getStackHook&&(n.stackTrace=c.Deferred.getStackHook()),
m.setTimeout(n))}}var g=0;return c.Deferred(function(g){b[0][3].add(f(0,g,c.isFunction(e)?e:ka,g.notifyWith));b[1][3].add(f(0,g,c.isFunction(a)?a:ka));b[2][3].add(f(0,g,c.isFunction(d)?d:la))}).promise()},promise:function(a){return null!=a?c.extend(a,e):e}},f={};c.each(b,function(a,c){var g=c[2],h=c[5];e[c[1]]=g.add;h&&g.add(function(){d=h},b[3-a][2].disable,b[0][2].lock);g.add(c[3].fire);f[c[0]]=function(){f[c[0]+"With"](this===f?void 0:this,arguments);return this};f[c[0]+"With"]=g.fireWith});e.promise(f);
a&&a.call(f,f);return f},when:function(a){var b=arguments.length,d=b,e=Array(d),f=ea.call(arguments),g=c.Deferred(),h=function(a){return function(c){e[a]=this;f[a]=1<arguments.length?ea.call(arguments):c;--b||g.resolveWith(e,f)}};if(1>=b&&($a(a,g.done(h(d)).resolve,g.reject),"pending"===g.state()||c.isFunction(f[d]&&f[d].then)))return g.then();for(;d--;)$a(f[d],h(d),g.reject);return g.promise()}});var kc=/^(Eval|Internal|Range|Reference|Syntax|Type|URI)Error$/;c.Deferred.exceptionHook=function(a,
b){m.console&&m.console.warn&&a&&kc.test(a.name)&&m.console.warn("jQuery.Deferred exception: "+a.message,a.stack,b)};var Va=c.Deferred();c.fn.ready=function(a){Va.then(a);return this};c.extend({isReady:!1,readyWait:1,holdReady:function(a){a?c.readyWait++:c.ready(!0)},ready:function(a){(!0===a?--c.readyWait:c.isReady)||(c.isReady=!0,!0!==a&&0<--c.readyWait||Va.resolveWith(q,[c]))}});c.ready.then=Va.then;"complete"===q.readyState||"loading"!==q.readyState&&!q.documentElement.doScroll?m.setTimeout(c.ready):
(q.addEventListener("DOMContentLoaded",ba),m.addEventListener("load",ba));var Z=function(a,b,d,e,f,g,h){var l=0,k=a.length,n=null==d;if("object"===c.type(d))for(l in f=!0,d)Z(a,b,l,d[l],!0,g,h);else if(void 0!==e&&(f=!0,c.isFunction(e)||(h=!0),n&&(h?(b.call(a,e),b=null):(n=b,b=function(a,b,d){return n.call(c(a),d)})),b))for(;l<k;l++)b(a[l],d,h?e:e.call(a[l],l,b(a[l],d)));return f?a:n?b.call(a):k?b(a[0],d):g},Ma=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};va.uid=1;va.prototype=
{cache:function(a){var b=a[this.expando];b||(b={},Ma(a)&&(a.nodeType?a[this.expando]=b:Object.defineProperty(a,this.expando,{value:b,configurable:!0})));return b},set:function(a,b,d){var e;a=this.cache(a);if("string"===typeof b)a[c.camelCase(b)]=d;else for(e in b)a[c.camelCase(e)]=b[e];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][c.camelCase(b)]},access:function(a,b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return this.get(a,b);this.set(a,
b,c);return void 0!==c?c:b},remove:function(a,b){var d,e=a[this.expando];if(void 0!==e){if(void 0!==b)for(c.isArray(b)?b=b.map(c.camelCase):(b=c.camelCase(b),b=b in e?[b]:b.match(S)||[]),d=b.length;d--;)delete e[b[d]];if(void 0===b||c.isEmptyObject(e))a.nodeType?a[this.expando]=void 0:delete a[this.expando]}},hasData:function(a){a=a[this.expando];return void 0!==a&&!c.isEmptyObject(a)}};var x=new va,J=new va,Rb=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Qb=/[A-Z]/g;c.extend({hasData:function(a){return J.hasData(a)||
x.hasData(a)},data:function(a,b,c){return J.access(a,b,c)},removeData:function(a,b){J.remove(a,b)},_data:function(a,b,c){return x.access(a,b,c)},_removeData:function(a,b){x.remove(a,b)}});c.fn.extend({data:function(a,b){var d,e=this[0],f=e&&e.attributes;if(void 0===a){if(this.length){var g=J.get(e);if(1===e.nodeType&&!x.get(e,"hasDataAttrs")){for(d=f.length;d--;)if(f[d]){var h=f[d].name;0===h.indexOf("data-")&&(h=c.camelCase(h.slice(5)),ab(e,h,g[h]))}x.set(e,"hasDataAttrs",!0)}}return g}return"object"===
typeof a?this.each(function(){J.set(this,a)}):Z(this,function(b){if(e&&void 0===b){var c=J.get(e,a);if(void 0!==c)return c;c=ab(e,a);if(void 0!==c)return c}else this.each(function(){J.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){J.remove(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=x.get(a,b);d&&(!e||c.isArray(d)?e=x.access(a,b,c.makeArray(d)):e.push(d));return e||[]}},dequeue:function(a,b){b=b||"fx";var d=
c.queue(a,b),e=d.length,f=d.shift(),g=c._queueHooks(a,b),h=function(){c.dequeue(a,b)};"inprogress"===f&&(f=d.shift(),e--);f&&("fx"===b&&d.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return x.get(a,d)||x.access(a,d,{empty:c.Callbacks("once memory").add(function(){x.remove(a,[b+"queue",d])})})}});c.fn.extend({queue:function(a,b){var d=2;"string"!==typeof a&&(b=a,a="fx",d--);return arguments.length<d?c.queue(this[0],a):void 0===
b?this:this.each(function(){var d=c.queue(this,a,b);c._queueHooks(this,a);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,h=this.length,l=function(){--e||f.resolveWith(g,[g])};"string"!==typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(d=x.get(g[h],a+"queueHooks"))&&d.empty&&(e++,d.empty.add(l));l();return f.promise(b)}});
var Eb=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,ca=new RegExp("^(?:([+-])=|)("+Eb+")([a-z%]*)$","i"),da=["Top","Right","Bottom","Left"],wa=function(a,b){a=b||a;return"none"===a.style.display||""===a.style.display&&c.contains(a.ownerDocument,a)&&"none"===c.css(a,"display")},Fb=function(a,b,c,e){var d,g={};for(d in b)g[d]=a.style[d],a.style[d]=b[d];c=c.apply(a,e||[]);for(d in b)a.style[d]=g[d];return c},cb={};c.fn.extend({show:function(){return ma(this,!0)},hide:function(){return ma(this)},toggle:function(a){return"boolean"===
typeof a?a?this.show():this.hide():this.each(function(){wa(this)?c(this).show():c(this).hide()})}});var Gb=/^(?:checkbox|radio)$/i,eb=/<([a-z][^\/\0>\x20\t\r\n\f]+)/i,fb=/^$|\/(?:java|ecma)script/i,O={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};O.optgroup=O.option;O.tbody=O.tfoot=O.colgroup=O.caption=
O.thead;O.th=O.td;var Sb=/<|&#?\w+;/;(function(){var a=q.createDocumentFragment().appendChild(q.createElement("div")),b=q.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);z.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";z.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue})();var Na=q.documentElement,lc=/^key/,mc=/^(?:mouse|pointer|contextmenu|drag|drop)|click/,
Hb=/^([^.]*)(?:\.(.+)|)/;c.event={global:{},add:function(a,b,d,e,f){var g,h,l,k,n;if(l=x.get(a)){if(d.handler){var m=d;d=m.handler;f=m.selector}f&&c.find.matchesSelector(Na,f);d.guid||(d.guid=c.guid++);(h=l.events)||(h=l.events={});(g=l.handle)||(g=l.handle=function(b){return"undefined"!==typeof c&&c.event.triggered!==b.type?c.event.dispatch.apply(a,arguments):void 0});b=(b||"").match(S)||[""];for(l=b.length;l--;){var A=Hb.exec(b[l])||[];var v=k=A[1];var p=(A[2]||"").split(".").sort();v&&(A=c.event.special[v]||
{},v=(f?A.delegateType:A.bindType)||v,A=c.event.special[v]||{},k=c.extend({type:v,origType:k,data:e,handler:d,guid:d.guid,selector:f,needsContext:f&&c.expr.match.needsContext.test(f),namespace:p.join(".")},m),(n=h[v])||(n=h[v]=[],n.delegateCount=0,A.setup&&!1!==A.setup.call(a,e,p,g)||a.addEventListener&&a.addEventListener(v,g)),A.add&&(A.add.call(a,k),k.handler.guid||(k.handler.guid=d.guid)),f?n.splice(n.delegateCount++,0,k):n.push(k),c.event.global[v]=!0)}}},remove:function(a,b,d,e,f){var g,h,l,
k,n,m=x.hasData(a)&&x.get(a);if(m&&(l=m.events)){b=(b||"").match(S)||[""];for(k=b.length;k--;){var p=Hb.exec(b[k])||[];var v=n=p[1];var r=(p[2]||"").split(".").sort();if(v){var q=c.event.special[v]||{};v=(e?q.delegateType:q.bindType)||v;var t=l[v]||[];p=p[2]&&new RegExp("(^|\\.)"+r.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=t.length;g--;){var z=t[g];!f&&n!==z.origType||d&&d.guid!==z.guid||p&&!p.test(z.namespace)||e&&e!==z.selector&&("**"!==e||!z.selector)||(t.splice(g,1),z.selector&&t.delegateCount--,
q.remove&&q.remove.call(a,z))}h&&!t.length&&(q.teardown&&!1!==q.teardown.call(a,r,m.handle)||c.removeEvent(a,v,m.handle),delete l[v])}else for(v in l)c.event.remove(a,v+b[k],d,e,!0)}c.isEmptyObject(l)&&x.remove(a,"handle events")}},dispatch:function(a){var b=c.event.fix(a),d,e,f,g=Array(arguments.length);var h=(x.get(this,"events")||{})[b.type]||[];var l=c.event.special[b.type]||{};g[0]=b;for(d=1;d<arguments.length;d++)g[d]=arguments[d];b.delegateTarget=this;if(!l.preDispatch||!1!==l.preDispatch.call(this,
b)){var k=c.event.handlers.call(this,b,h);for(d=0;(f=k[d++])&&!b.isPropagationStopped();)for(b.currentTarget=f.elem,h=0;(e=f.handlers[h++])&&!b.isImmediatePropagationStopped();)if(!b.rnamespace||b.rnamespace.test(e.namespace))b.handleObj=e,b.data=e.data,e=((c.event.special[e.origType]||{}).handle||e.handler).apply(f.elem,g),void 0!==e&&!1===(b.result=e)&&(b.preventDefault(),b.stopPropagation());l.postDispatch&&l.postDispatch.call(this,b);return b.result}},handlers:function(a,b){var d,e=[],f=b.delegateCount,
g=a.target;if(f&&g.nodeType&&("click"!==a.type||isNaN(a.button)||1>a.button))for(;g!==this;g=g.parentNode||this)if(1===g.nodeType&&(!0!==g.disabled||"click"!==a.type)){var h=[];for(d=0;d<f;d++){var l=b[d];var k=l.selector+" ";void 0===h[k]&&(h[k]=l.needsContext?-1<c(k,this).index(g):c.find(k,this,null,[g]).length);h[k]&&h.push(l)}h.length&&e.push({elem:g,handlers:h})}f<b.length&&e.push({elem:this,handlers:b.slice(f)});return e},addProp:function(a,b){Object.defineProperty(c.Event.prototype,a,{enumerable:!0,
configurable:!0,get:c.isFunction(b)?function(){if(this.originalEvent)return b(this.originalEvent)}:function(){if(this.originalEvent)return this.originalEvent[a]},set:function(b){Object.defineProperty(this,a,{enumerable:!0,configurable:!0,writable:!0,value:b})}})},fix:function(a){return a[c.expando]?a:new c.Event(a)},special:{load:{noBubble:!0},focus:{trigger:function(){if(this!==gb()&&this.focus)return this.focus(),!1},delegateType:"focusin"},blur:{trigger:function(){if(this===gb()&&this.blur)return this.blur(),
!1},delegateType:"focusout"},click:{trigger:function(){if("checkbox"===this.type&&this.click&&c.nodeName(this,"input"))return this.click(),!1},_default:function(a){return c.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&a.originalEvent&&(a.originalEvent.returnValue=a.result)}}}};c.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c)};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);a&&a.type?(this.originalEvent=
a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?Ba:na,this.target=a.target&&3===a.target.nodeType?a.target.parentNode:a.target,this.currentTarget=a.currentTarget,this.relatedTarget=a.relatedTarget):this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||c.now();this[c.expando]=!0};c.Event.prototype={constructor:c.Event,isDefaultPrevented:na,isPropagationStopped:na,isImmediatePropagationStopped:na,isSimulated:!1,preventDefault:function(){var a=
this.originalEvent;this.isDefaultPrevented=Ba;a&&!this.isSimulated&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=Ba;a&&!this.isSimulated&&a.stopPropagation()},stopImmediatePropagation:function(){var a=this.originalEvent;this.isImmediatePropagationStopped=Ba;a&&!this.isSimulated&&a.stopImmediatePropagation();this.stopPropagation()}};c.each({altKey:!0,bubbles:!0,cancelable:!0,changedTouches:!0,ctrlKey:!0,detail:!0,eventPhase:!0,metaKey:!0,pageX:!0,
pageY:!0,shiftKey:!0,view:!0,"char":!0,charCode:!0,key:!0,keyCode:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pointerId:!0,pointerType:!0,screenX:!0,screenY:!0,targetTouches:!0,toElement:!0,touches:!0,which:function(a){var b=a.button;return null==a.which&&lc.test(a.type)?null!=a.charCode?a.charCode:a.keyCode:!a.which&&void 0!==b&&mc.test(a.type)?b&1?1:b&2?3:b&4?2:0:a.which}},c.event.addProp);c.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},
function(a,b){c.event.special[a]={delegateType:b,bindType:b,handle:function(a){var d=a.relatedTarget,f=a.handleObj;if(!d||d!==this&&!c.contains(this,d)){a.type=f.origType;var g=f.handler.apply(this,arguments);a.type=b}return g}}});c.fn.extend({on:function(a,b,c,e){return Pa(this,a,b,c,e)},one:function(a,b,c,e){return Pa(this,a,b,c,e,1)},off:function(a,b,d){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);
return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)d=b,b=void 0;!1===d&&(d=na);return this.each(function(){c.event.remove(this,a,d,b)})}});var nc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([a-z][^\/\0>\x20\t\r\n\f]*)[^>]*)\/>/gi,oc=/<script|<style|<link/i,Wb=/checked\s*(?:[^=]|=\s*.checked.)/i,Vb=/^true\/(.*)/,Xb=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;c.extend({htmlPrefilter:function(a){return a.replace(nc,"<$1></$2>")},clone:function(a,
b,d){var e,f=a.cloneNode(!0),g=c.contains(a.ownerDocument,a);if(!(z.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||c.isXMLDoc(a))){var h=F(f);var l=F(a);var k=0;for(e=l.length;k<e;k++){var n=l[k],m=h[k],p=m.nodeName.toLowerCase();if("input"===p&&Gb.test(n.type))m.checked=n.checked;else if("input"===p||"textarea"===p)m.defaultValue=n.defaultValue}}if(b)if(d)for(l=l||F(a),h=h||F(f),k=0,e=l.length;k<e;k++)ib(l[k],h[k]);else ib(a,f);h=F(f,"script");0<h.length&&Oa(h,!g&&F(a,"script"));return f},cleanData:function(a){for(var b,
d,e,f=c.event.special,g=0;void 0!==(d=a[g]);g++)if(Ma(d)){if(b=d[x.expando]){if(b.events)for(e in b.events)f[e]?c.event.remove(d,e):c.removeEvent(d,e,b.handle);d[x.expando]=void 0}d[J.expando]&&(d[J.expando]=void 0)}}});c.fn.extend({detach:function(a){return kb(this,a,!0)},remove:function(a){return kb(this,a)},text:function(a){return Z(this,function(a){return void 0===a?c.text(this):this.empty().each(function(){if(1===this.nodeType||11===this.nodeType||9===this.nodeType)this.textContent=a})},null,
a,arguments.length)},append:function(){return oa(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||hb(this,a).appendChild(a)})},prepend:function(){return oa(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=hb(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return oa(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return oa(this,arguments,function(a){this.parentNode&&
this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(c.cleanData(F(a,!1)),a.textContent="");return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return Z(this,function(a){var b=this[0]||{},e=0,f=this.length;if(void 0===a&&1===b.nodeType)return b.innerHTML;if("string"===typeof a&&!oc.test(a)&&!O[(eb.exec(a)||["",""])[1].toLowerCase()]){a=c.htmlPrefilter(a);
try{for(;e<f;e++)b=this[e]||{},1===b.nodeType&&(c.cleanData(F(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=[];return oa(this,arguments,function(b){var d=this.parentNode;0>c.inArray(this,a)&&(c.cleanData(F(this)),d&&d.replaceChild(b,this))},a)}});c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(a){for(var d=[],f=c(a),g=f.length-1,
h=0;h<=g;h++)a=h===g?this:this.clone(!0),c(f[h])[b](a),Ua.apply(d,a.get());return this.pushStack(d)}});var lb=/^margin/,Qa=new RegExp("^("+Eb+")(?!px)[a-z%]+$","i"),Fa=function(a){var b=a.ownerDocument.defaultView;b&&b.opener||(b=m);return b.getComputedStyle(a)};(function(){function a(){if(h){h.style.cssText="box-sizing:border-box;position:relative;display:block;margin:auto;border:1px;padding:1px;top:1%;width:50%";h.innerHTML="";Na.appendChild(g);var a=m.getComputedStyle(h);b="1%"!==a.top;f="2px"===
a.marginLeft;d="4px"===a.width;h.style.marginRight="50%";e="4px"===a.marginRight;Na.removeChild(g);h=null}}var b,d,e,f,g=q.createElement("div"),h=q.createElement("div");h.style&&(h.style.backgroundClip="content-box",h.cloneNode(!0).style.backgroundClip="",z.clearCloneStyle="content-box"===h.style.backgroundClip,g.style.cssText="border:0;width:8px;height:0;top:0;left:-9999px;padding:0;margin-top:1px;position:absolute",g.appendChild(h),c.extend(z,{pixelPosition:function(){a();return b},boxSizingReliable:function(){a();
return d},pixelMarginRight:function(){a();return e},reliableMarginLeft:function(){a();return f}}))})();var pc=/^(none|table(?!-c[ea]).+)/,qc={position:"absolute",visibility:"hidden",display:"block"},Ib={letterSpacing:"0",fontWeight:"400"},pb=["Webkit","Moz","ms"],ob=q.createElement("div").style;c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=pa(a,"opacity");return""===c?"1":c}}}},cssNumber:{animationIterationCount:!0,columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,
lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,d,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g=c.camelCase(b),h=a.style;b=c.cssProps[g]||(c.cssProps[g]=nb(g)||g);var l=c.cssHooks[b]||c.cssHooks[g];if(void 0!==d){var k=typeof d;"string"===k&&(f=ca.exec(d))&&f[1]&&(d=bb(a,b,f),k="number");null!=d&&d===d&&("number"===k&&(d+=f&&f[3]||(c.cssNumber[g]?"":"px")),z.clearCloneStyle||""!==d||0!==b.indexOf("background")||
(h[b]="inherit"),l&&"set"in l&&void 0===(d=l.set(a,d,e))||(h[b]=d))}else return l&&"get"in l&&void 0!==(f=l.get(a,!1,e))?f:h[b]}},css:function(a,b,d,e){var f;var g=c.camelCase(b);b=c.cssProps[g]||(c.cssProps[g]=nb(g)||g);(g=c.cssHooks[b]||c.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,d));void 0===f&&(f=pa(a,b,e));"normal"===f&&b in Ib&&(f=Ib[b]);return""===d||d?(a=parseFloat(f),!0===d||isFinite(a)?a||0:f):f}});c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(a,e,f){if(e)return!pc.test(c.css(a,
"display"))||a.getClientRects().length&&a.getBoundingClientRect().width?sb(a,b,f):Fb(a,qc,function(){return sb(a,b,f)})},set:function(a,e,f){var d,h=f&&Fa(a);(f=f&&rb(a,b,f,"border-box"===c.css(a,"boxSizing",!1,h),h))&&(d=ca.exec(e))&&"px"!==(d[3]||"px")&&(a.style[b]=e,e=c.css(a,b));return qb(a,e,f)}}});c.cssHooks.marginLeft=mb(z.reliableMarginLeft,function(a,b){if(b)return(parseFloat(pa(a,"marginLeft"))||a.getBoundingClientRect().left-Fb(a,{marginLeft:0},function(){return a.getBoundingClientRect().left}))+
"px"});c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>d;d++)f[a+da[d]+b]=c[d]||c[d-2]||c[0];return f}};lb.test(a)||(c.cssHooks[a+b].set=qb)});c.fn.extend({css:function(a,b){return Z(this,function(a,b,f){var d,e={},l=0;if(c.isArray(b)){f=Fa(a);for(d=b.length;l<d;l++)e[b[l]]=c.css(a,b[l],!1,f);return e}return void 0!==f?c.style(a,b,f):c.css(a,b)},a,b,1<arguments.length)}});c.Tween=G;G.prototype=
{constructor:G,init:function(a,b,d,e,f,g){this.elem=a;this.prop=d;this.easing=f||c.easing._default;this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=G.propHooks[this.prop];return a&&a.get?a.get(this):G.propHooks._default.get(this)},run:function(a){var b,d=G.propHooks[this.prop];this.pos=this.options.duration?b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;
this.options.step&&this.options.step.call(this.elem,this.now,this);d&&d.set?d.set(this):G.propHooks._default.set(this);return this}};G.prototype.init.prototype=G.prototype;G.propHooks={_default:{get:function(a){return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(a=c.css(a.elem,a.prop,""))&&"auto"!==a?a:0},set:function(a){if(c.fx.step[a.prop])c.fx.step[a.prop](a);else 1!==a.elem.nodeType||null==a.elem.style[c.cssProps[a.prop]]&&!c.cssHooks[a.prop]?a.elem[a.prop]=
a.now:c.style(a.elem,a.prop,a.now+a.unit)}}};G.propHooks.scrollTop=G.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};c.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};c.fx=G.prototype.init;c.fx.step={};var qa,X,rc=/^(?:toggle|show|hide)$/,sc=/queueHooks$/;c.Animation=c.extend(H,{tweeners:{"*":[function(a,b){var c=this.createTween(a,b);bb(c.elem,a,ca.exec(b),c);return c}]},tweener:function(a,
b){c.isFunction(a)?(b=a,a=["*"]):a=a.match(S);for(var d,e=0,f=a.length;e<f;e++)d=a[e],H.tweeners[d]=H.tweeners[d]||[],H.tweeners[d].unshift(b)},prefilters:[function(a,b,d){var e;var f="width"in b||"height"in b;var g=this,h={},l=a.style,k=a.nodeType&&wa(a),n=x.get(a,"fxshow");if(!d.queue){var m=c._queueHooks(a,"fx");if(null==m.unqueued){m.unqueued=0;var p=m.empty.fire;m.empty.fire=function(){m.unqueued||p()}}m.unqueued++;g.always(function(){g.always(function(){m.unqueued--;c.queue(a,"fx").length||
m.empty.fire()})})}for(e in b){var v=b[e];if(rc.test(v)){delete b[e];var r=r||"toggle"===v;if(v===(k?"hide":"show"))if("show"===v&&n&&void 0!==n[e])k=!0;else continue;h[e]=n&&n[e]||c.style(a,e)}}if((b=!c.isEmptyObject(b))||!c.isEmptyObject(h)){if(f&&1===a.nodeType){d.overflow=[l.overflow,l.overflowX,l.overflowY];var q=n&&n.display;null==q&&(q=x.get(a,"display"));f=c.css(a,"display");"none"===f&&(q?f=q:(ma([a],!0),q=a.style.display||q,f=c.css(a,"display"),ma([a])));("inline"===f||"inline-block"===
f&&null!=q)&&"none"===c.css(a,"float")&&(b||(g.done(function(){l.display=q}),null==q&&(f=l.display,q="none"===f?"":f)),l.display="inline-block")}d.overflow&&(l.overflow="hidden",g.always(function(){l.overflow=d.overflow[0];l.overflowX=d.overflow[1];l.overflowY=d.overflow[2]}));b=!1;for(e in h)b||(n?"hidden"in n&&(k=n.hidden):n=x.access(a,"fxshow",{display:q}),r&&(n.hidden=!k),k&&ma([a],!0),g.done(function(){k||ma([a]);x.remove(a,"fxshow");for(e in h)c.style(a,e,h[e])})),b=vb(k?n[e]:0,e,g),e in n||
(n[e]=b.start,k&&(b.end=b.start,b.start=0))}}],prefilter:function(a,b){b?H.prefilters.unshift(a):H.prefilters.push(a)}});c.speed=function(a,b,d){var e=a&&"object"===typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off||q.hidden?0:"number"===typeof e.duration?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){c.isFunction(e.old)&&
e.old.call(this);e.queue&&c.dequeue(this,e.queue)};return e};c.fn.extend({fadeTo:function(a,b,c,e){return this.filter(wa).css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,e);b=function(){var b=H(this,c.extend({},a),g);(f||x.get(this,"finish"))&&b.stop(!0)};b.finish=b;return f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,d){var e=function(a){var b=a.stop;delete a.stop;b(d)};"string"!==typeof a&&(d=b,b=
a,a=void 0);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=c.timers,l=x.get(this);if(g)l[g]&&l[g].stop&&e(l[g]);else for(g in l)l[g]&&l[g].stop&&sc.test(g)&&e(l[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(d),b=!1,h.splice(g,1));!b&&d||c.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b=x.get(this),d=b[a+"queue"];var e=b[a+"queueHooks"];var f=c.timers,g=d?d.length:0;
b.finish=!0;c.queue(this,a,[]);e&&e.stop&&e.stop.call(this,!0);for(e=f.length;e--;)f[e].elem===this&&f[e].queue===a&&(f[e].anim.stop(!0),f.splice(e,1));for(e=0;e<g;e++)d[e]&&d[e].finish&&d[e].finish.call(this);delete b.finish})}});c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(a,c,g){return null==a||"boolean"===typeof a?d.apply(this,arguments):this.animate(Ga(b,!0),a,c,g)}});c.each({slideDown:Ga("show"),slideUp:Ga("hide"),slideToggle:Ga("toggle"),fadeIn:{opacity:"show"},
fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(a,c,f){return this.animate(b,a,c,f)}});c.timers=[];c.fx.tick=function(){var a=0,b=c.timers;for(qa=c.now();a<b.length;a++){var d=b[a];d()||b[a]!==d||b.splice(a--,1)}b.length||c.fx.stop();qa=void 0};c.fx.timer=function(a){c.timers.push(a);a()?c.fx.start():c.timers.pop()};c.fx.interval=13;c.fx.start=function(){X||(X=m.requestAnimationFrame?m.requestAnimationFrame(tb):m.setInterval(c.fx.tick,c.fx.interval))};c.fx.stop=
function(){m.cancelAnimationFrame?m.cancelAnimationFrame(X):m.clearInterval(X);X=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fn.delay=function(a,b){a=c.fx?c.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,c){var d=m.setTimeout(b,a);c.stop=function(){m.clearTimeout(d)}})};(function(){var a=q.createElement("input"),b=q.createElement("select").appendChild(q.createElement("option"));a.type="checkbox";z.checkOn=""!==a.value;z.optSelected=b.selected;a=q.createElement("input");a.value="t";
a.type="radio";z.radioValue="t"===a.value})();var ta=c.expr.attrHandle;c.fn.extend({attr:function(a,b){return Z(this,c.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})}});c.extend({attr:function(a,b,d){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g){if("undefined"===typeof a.getAttribute)return c.prop(a,b,d);1===g&&c.isXMLDoc(a)||(f=c.attrHooks[b.toLowerCase()]||(c.expr.match.bool.test(b)?tc:void 0));if(void 0!==d){if(null===d){c.removeAttr(a,b);
return}if(f&&"set"in f&&void 0!==(e=f.set(a,d,b)))return e;a.setAttribute(b,d+"");return d}if(f&&"get"in f&&null!==(e=f.get(a,b)))return e;e=c.find.attr(a,b);return null==e?void 0:e}},attrHooks:{type:{set:function(a,b){if(!z.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);d&&(a.value=d);return b}}}},removeAttr:function(a,b){var c,e=0,f=b&&b.match(S);if(f&&1===a.nodeType)for(;c=f[e++];)a.removeAttribute(c)}});var tc={set:function(a,b,d){!1===b?c.removeAttr(a,
d):a.setAttribute(d,d);return d}};c.each(c.expr.match.bool.source.match(/\w+/g),function(a,b){var d=ta[b]||c.find.attr;ta[b]=function(a,b,c){var e=b.toLowerCase();if(!c){var f=ta[e];ta[e]=g;var g=null!=d(a,b,c)?e:null;ta[e]=f}return g}});var uc=/^(?:input|select|textarea|button)$/i,vc=/^(?:a|area)$/i;c.fn.extend({prop:function(a,b){return Z(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[c.propFix[a]||a]})}});c.extend({prop:function(a,b,d){var e,
f=a.nodeType;if(3!==f&&8!==f&&2!==f){if(1!==f||!c.isXMLDoc(a)){b=c.propFix[b]||b;var g=c.propHooks[b]}return void 0!==d?g&&"set"in g&&void 0!==(e=g.set(a,d,b))?e:a[b]=d:g&&"get"in g&&null!==(e=g.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=c.find.attr(a,"tabindex");return b?parseInt(b,10):uc.test(a.nodeName)||vc.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor","class":"className"}});z.optSelected||(c.propHooks.selected={get:function(a){(a=a.parentNode)&&a.parentNode&&a.parentNode.selectedIndex;
return null},set:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex}});c.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){c.propFix[this.toLowerCase()]=this});var Wa=/[\t\r\n\f]/g;c.fn.extend({addClass:function(a){var b,d,e,f,g,h=0;if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,aa(this)))});if("string"===typeof a&&a)for(b=a.match(S)||[];d=this[h++];){var l=
aa(d);if(e=1===d.nodeType&&(" "+l+" ").replace(Wa," ")){for(g=0;f=b[g++];)0>e.indexOf(" "+f+" ")&&(e+=f+" ");e=c.trim(e);l!==e&&d.setAttribute("class",e)}}return this},removeClass:function(a){var b,d,e,f,g,h=0;if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,b,aa(this)))});if(!arguments.length)return this.attr("class","");if("string"===typeof a&&a)for(b=a.match(S)||[];d=this[h++];){var l=aa(d);if(e=1===d.nodeType&&(" "+l+" ").replace(Wa," ")){for(g=0;f=b[g++];)for(;-1<
e.indexOf(" "+f+" ");)e=e.replace(" "+f+" "," ");e=c.trim(e);l!==e&&d.setAttribute("class",e)}}return this},toggleClass:function(a,b){var d=typeof a;return"boolean"===typeof b&&"string"===d?b?this.addClass(a):this.removeClass(a):c.isFunction(a)?this.each(function(d){c(this).toggleClass(a.call(this,d,aa(this),b),b)}):this.each(function(){var b,f;if("string"===d){var g=0;var h=c(this);for(f=a.match(S)||[];b=f[g++];)h.hasClass(b)?h.removeClass(b):h.addClass(b)}else if(void 0===a||"boolean"===d)(b=aa(this))&&
x.set(this,"__className__",b),this.setAttribute&&this.setAttribute("class",b||!1===a?"":x.get(this,"__className__")||"")})},hasClass:function(a){var b,c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+aa(b)+" ").replace(Wa," ").indexOf(a))return!0;return!1}});var wc=/\r/g,xc=/[\x20\t\r\n\f]+/g;c.fn.extend({val:function(a){var b,d,e=this[0];if(arguments.length){var f=c.isFunction(a);return this.each(function(d){1===this.nodeType&&(d=f?a.call(this,d,c(this).val()):a,null==d?d="":"number"===
typeof d?d+="":c.isArray(d)&&(d=c.map(d,function(a){return null==a?"":a+""})),b=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,d,"value")||(this.value=d))})}if(e){if((b=c.valHooks[e.type]||c.valHooks[e.nodeName.toLowerCase()])&&"get"in b&&void 0!==(d=b.get(e,"value")))return d;d=e.value;return"string"===typeof d?d.replace(wc,""):null==d?"":d}}});c.extend({valHooks:{option:{get:function(a){var b=c.find.attr(a,"value");return null!=b?b:c.trim(c.text(a)).replace(xc,
" ")}},select:{get:function(a){for(var b,d=a.options,e=a.selectedIndex,f=(a="select-one"===a.type)?null:[],g=a?e+1:d.length,h=0>e?g:a?e:0;h<g;h++)if(b=d[h],!(!b.selected&&h!==e||b.disabled||b.parentNode.disabled&&c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();if(a)return b;f.push(b)}return f},set:function(a,b){for(var d,e,f=a.options,g=c.makeArray(b),h=f.length;h--;)if(e=f[h],e.selected=-1<c.inArray(c.valHooks.option.get(e),g))d=!0;d||(a.selectedIndex=-1);return g}}}});c.each(["radio","checkbox"],
function(){c.valHooks[this]={set:function(a,b){if(c.isArray(b))return a.checked=-1<c.inArray(c(a).val(),b)}};z.checkOn||(c.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});var Jb=/^(?:focusinfocus|focusoutblur)$/;c.extend(c.event,{trigger:function(a,b,d,e){var f,g,h=[d||q],l=Ia.call(a,"type")?a.type:a;var k=Ia.call(a,"namespace")?a.namespace.split("."):[];var n=f=d=d||q;if(3!==d.nodeType&&8!==d.nodeType&&!Jb.test(l+c.event.triggered)){-1<l.indexOf(".")&&(k=l.split("."),
l=k.shift(),k.sort());var p=0>l.indexOf(":")&&"on"+l;a=a[c.expando]?a:new c.Event(l,"object"===typeof a&&a);a.isTrigger=e?2:3;a.namespace=k.join(".");a.rnamespace=a.namespace?new RegExp("(^|\\.)"+k.join("\\.(?:.*\\.|)")+"(\\.|$)"):null;a.result=void 0;a.target||(a.target=d);b=null==b?[a]:c.makeArray(b,[a]);k=c.event.special[l]||{};if(e||!k.trigger||!1!==k.trigger.apply(d,b)){if(!e&&!k.noBubble&&!c.isWindow(d)){var r=k.delegateType||l;Jb.test(r+l)||(n=n.parentNode);for(;n;n=n.parentNode)h.push(n),
f=n;f===(d.ownerDocument||q)&&h.push(f.defaultView||f.parentWindow||m)}for(f=0;(n=h[f++])&&!a.isPropagationStopped();)a.type=1<f?r:k.bindType||l,(g=(x.get(n,"events")||{})[a.type]&&x.get(n,"handle"))&&g.apply(n,b),(g=p&&n[p])&&g.apply&&Ma(n)&&(a.result=g.apply(n,b),!1===a.result&&a.preventDefault());a.type=l;e||a.isDefaultPrevented()||k._default&&!1!==k._default.apply(h.pop(),b)||!Ma(d)||!p||!c.isFunction(d[l])||c.isWindow(d)||((f=d[p])&&(d[p]=null),c.event.triggered=l,d[l](),c.event.triggered=void 0,
f&&(d[p]=f));return a.result}}},simulate:function(a,b,d){a=c.extend(new c.Event,d,{type:a,isSimulated:!0});c.event.trigger(a,null,b)}});c.fn.extend({trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){var d=this[0];if(d)return c.event.trigger(a,b,d,!0)}});c.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu".split(" "),
function(a,b){c.fn[b]=function(a,c){return 0<arguments.length?this.on(b,null,a,c):this.trigger(b)}});c.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});z.focusin="onfocusin"in m;z.focusin||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=function(a){c.event.simulate(b,a.target,c.event.fix(a))};c.event.special[b]={setup:function(){var c=this.ownerDocument||this,f=x.access(c,b);f||c.addEventListener(a,d,!0);x.access(c,b,(f||0)+1)},teardown:function(){var c=this.ownerDocument||
this,f=x.access(c,b)-1;f?x.access(c,b,f):(c.removeEventListener(a,d,!0),x.remove(c,b))}}});var ua=m.location,Kb=c.now(),Xa=/\?/;c.parseXML=function(a){if(!a||"string"!==typeof a)return null;try{var b=(new m.DOMParser).parseFromString(a,"text/xml")}catch(d){b=void 0}b&&!b.getElementsByTagName("parsererror").length||c.error("Invalid XML: "+a);return b};var Zb=/\[\]$/,Lb=/\r?\n/g,yc=/^(?:submit|button|image|reset|file)$/i,zc=/^(?:input|select|textarea|keygen)/i;c.param=function(a,b){var d,e=[],f=function(a,
b){var d=c.isFunction(b)?b():b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(null==d?"":d)};if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){f(this.name,this.value)});else for(d in a)Ra(d,a[d],b,f);return e.join("&")};c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=c.prop(this,"elements");return a?c.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!c(this).is(":disabled")&&
zc.test(this.nodeName)&&!yc.test(a)&&(this.checked||!Gb.test(a))}).map(function(a,b){var d=c(this).val();return null==d?null:c.isArray(d)?c.map(d,function(a){return{name:b.name,value:a.replace(Lb,"\r\n")}}):{name:b.name,value:d.replace(Lb,"\r\n")}}).get()}});var Ac=/%20/g,Bc=/#.*$/,Cc=/([?&])_=[^&]*/,Dc=/^(.*?):[ \t]*([^\r\n]*)$/mg,Ec=/^(?:GET|HEAD)$/,Fc=/^\/\//,Mb={},Sa={},Nb="*/".concat("*"),Ya=q.createElement("a");Ya.href=ua.href;c.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:ua.href,
type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(ua.protocol),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Nb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":JSON.parse,
"text xml":c.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Ta(Ta(a,c.ajaxSettings),b):Ta(c.ajaxSettings,a)},ajaxPrefilter:wb(Mb),ajaxTransport:wb(Sa),ajax:function(a,b){function d(a,b,d,g){var k=b;if(!J){J=!0;h&&m.clearTimeout(h);e=void 0;f=g||"";B.readyState=0<a?4:0;g=200<=a&&300>a||304===a;if(d){var q=n;for(var t=B,y,M,D,w,C=q.contents,A=q.dataTypes;"*"===A[0];)A.shift(),void 0===y&&(y=q.mimeType||t.getResponseHeader("Content-Type"));if(y)for(M in C)if(C[M]&&C[M].test(y)){A.unshift(M);
break}if(A[0]in d)D=A[0];else{for(M in d){if(!A[0]||q.converters[M+" "+A[0]]){D=M;break}w||(w=M)}D=D||w}D?(D!==A[0]&&A.unshift(D),q=d[D]):q=void 0}a:{d=n;y=q;M=B;D=g;var F;t={};C=d.dataTypes.slice();if(C[1])for(P in d.converters)t[P.toLowerCase()]=d.converters[P];for(w=C.shift();w;){d.responseFields[w]&&(M[d.responseFields[w]]=y);!H&&D&&d.dataFilter&&(y=d.dataFilter(y,d.dataType));var H=w;if(w=C.shift())if("*"===w)w=H;else if("*"!==H&&H!==w){var P=t[H+" "+w]||t["* "+w];if(!P)for(F in t)if(q=F.split(" "),
q[1]===w&&(P=t[H+" "+q[0]]||t["* "+q[0]])){!0===P?P=t[F]:!0!==t[F]&&(w=q[0],C.unshift(q[1]));break}if(!0!==P)if(P&&d["throws"])y=P(y);else try{y=P(y)}catch(fc){q={state:"parsererror",error:P?fc:"No conversion from "+H+" to "+w};break a}}}q={state:"success",data:y}}if(g)if(n.ifModified&&((k=B.getResponseHeader("Last-Modified"))&&(c.lastModified[G]=k),(k=B.getResponseHeader("etag"))&&(c.etag[G]=k)),204===a||"HEAD"===n.type)k="nocontent";else if(304===a)k="notmodified";else{k=q.state;var O=q.data;var N=
q.error;g=!N}else if(N=k,a||!k)k="error",0>a&&(a=0);B.status=a;B.statusText=(b||k)+"";g?v.resolveWith(p,[O,k,B]):v.rejectWith(p,[B,k,N]);B.statusCode(z);z=void 0;l&&r.trigger(g?"ajaxSuccess":"ajaxError",[B,n,g?O:N]);x.fireWith(p,[B,k]);l&&(r.trigger("ajaxComplete",[B,n]),--c.active||c.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=void 0);b=b||{};var e,f,g,h,l,k,n=c.ajaxSetup({},b),p=n.context||n,r=n.context&&(p.nodeType||p.jquery)?c(p):c.event,v=c.Deferred(),x=c.Callbacks("once memory"),
z=n.statusCode||{},t={},w={},H="canceled",B={readyState:0,getResponseHeader:function(a){var b;if(J){if(!g)for(g={};b=Dc.exec(f);)g[b[1].toLowerCase()]=b[2];b=g[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return J?f:null},setRequestHeader:function(a,b){null==J&&(a=w[a.toLowerCase()]=w[a.toLowerCase()]||a,t[a]=b);return this},overrideMimeType:function(a){null==J&&(n.mimeType=a);return this},statusCode:function(a){var b;if(a)if(J)B.always(a[B.status]);else for(b in a)z[b]=
[z[b],a[b]];return this},abort:function(a){a=a||H;e&&e.abort(a);d(0,a);return this}};v.promise(B);n.url=((a||n.url||ua.href)+"").replace(Fc,ua.protocol+"//");n.type=b.method||b.type||n.method||n.type;n.dataTypes=(n.dataType||"*").toLowerCase().match(S)||[""];if(null==n.crossDomain){var F=q.createElement("a");try{F.href=n.url,F.href=F.href,n.crossDomain=Ya.protocol+"//"+Ya.host!==F.protocol+"//"+F.host}catch(M){n.crossDomain=!0}}n.data&&n.processData&&"string"!==typeof n.data&&(n.data=c.param(n.data,
n.traditional));xb(Mb,n,b,B);if(J)return B;(l=c.event&&n.global)&&0===c.active++&&c.event.trigger("ajaxStart");n.type=n.type.toUpperCase();n.hasContent=!Ec.test(n.type);var G=n.url.replace(Bc,"");n.hasContent?n.data&&n.processData&&0===(n.contentType||"").indexOf("application/x-www-form-urlencoded")&&(n.data=n.data.replace(Ac,"+")):(F=n.url.slice(G.length),n.data&&(G+=(Xa.test(G)?"&":"?")+n.data,delete n.data),!1===n.cache&&(G=G.replace(Cc,""),F=(Xa.test(G)?"&":"?")+"_="+Kb++ +F),n.url=G+F);n.ifModified&&
(c.lastModified[G]&&B.setRequestHeader("If-Modified-Since",c.lastModified[G]),c.etag[G]&&B.setRequestHeader("If-None-Match",c.etag[G]));(n.data&&n.hasContent&&!1!==n.contentType||b.contentType)&&B.setRequestHeader("Content-Type",n.contentType);B.setRequestHeader("Accept",n.dataTypes[0]&&n.accepts[n.dataTypes[0]]?n.accepts[n.dataTypes[0]]+("*"!==n.dataTypes[0]?", "+Nb+"; q=0.01":""):n.accepts["*"]);for(k in n.headers)B.setRequestHeader(k,n.headers[k]);if(n.beforeSend&&(!1===n.beforeSend.call(p,B,n)||
J))return B.abort();H="abort";x.add(n.complete);B.done(n.success);B.fail(n.error);if(e=xb(Sa,n,b,B)){B.readyState=1;l&&r.trigger("ajaxSend",[B,n]);if(J)return B;n.async&&0<n.timeout&&(h=m.setTimeout(function(){B.abort("timeout")},n.timeout));try{var J=!1;e.send(t,d)}catch(M){if(J)throw M;d(-1,M)}}else d(-1,"No Transport");return B},getJSON:function(a,b,d){return c.get(a,b,d,"json")},getScript:function(a,b){return c.get(a,void 0,b,"script")}});c.each(["get","post"],function(a,b){c[b]=function(a,e,
f,g){c.isFunction(e)&&(g=g||f,f=e,e=void 0);return c.ajax(c.extend({url:a,type:b,dataType:g,data:e,success:f},c.isPlainObject(a)&&a))}});c._evalUrl=function(a){return c.ajax({url:a,type:"GET",dataType:"script",cache:!0,async:!1,global:!1,"throws":!0})};c.fn.extend({wrapAll:function(a){this[0]&&(c.isFunction(a)&&(a=a.call(this[0])),a=c(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&a.insertBefore(this[0]),a.map(function(){for(var a=this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this));
return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?a.call(this,d):a)})},unwrap:function(a){this.parent(a).not("body").each(function(){c(this).replaceWith(this.childNodes)});return this}});c.expr.pseudos.hidden=function(a){return!c.expr.pseudos.visible(a)};c.expr.pseudos.visible=
function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)};c.ajaxSettings.xhr=function(){try{return new m.XMLHttpRequest}catch(a){}};var Gc={0:200,1223:204},za=c.ajaxSettings.xhr();z.cors=!!za&&"withCredentials"in za;z.ajax=za=!!za;c.ajaxTransport(function(a){var b,c;if(z.cors||za&&!a.crossDomain)return{send:function(d,f){var e,h=a.xhr();h.open(a.type,a.url,a.async,a.username,a.password);if(a.xhrFields)for(e in a.xhrFields)h[e]=a.xhrFields[e];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);
a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");for(e in d)h.setRequestHeader(e,d[e]);b=function(a){return function(){b&&(b=c=h.onload=h.onerror=h.onabort=h.onreadystatechange=null,"abort"===a?h.abort():"error"===a?"number"!==typeof h.status?f(0,"error"):f(h.status,h.statusText):f(Gc[h.status]||h.status,h.statusText,"text"!==(h.responseType||"text")||"string"!==typeof h.responseText?{binary:h.response}:{text:h.responseText},h.getAllResponseHeaders()))}};h.onload=b();
c=h.onerror=b("error");void 0!==h.onabort?h.onabort=c:h.onreadystatechange=function(){4===h.readyState&&m.setTimeout(function(){b&&c()})};b=b("abort");try{h.send(a.hasContent&&a.data||null)}catch(l){if(b)throw l;}},abort:function(){b&&b()}}});c.ajaxPrefilter(function(a){a.crossDomain&&(a.contents.script=!1)});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/\b(?:java|ecma)script\b/},converters:{"text script":function(a){c.globalEval(a);
return a}}});c.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,d;return{send:function(e,f){b=c("<script>").prop({charset:a.scriptCharset,src:a.url}).on("load error",d=function(a){b.remove();d=null;a&&f("error"===a.type?404:200,a.type)});q.head.appendChild(b[0])},abort:function(){d&&d()}}}});var Ob=[],Za=/(=)\?(?=&|$)|\?\?/;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Ob.pop()||
c.expando+"_"+Kb++;this[a]=!0;return a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var e,f=!1!==a.jsonp&&(Za.test(a.url)?"url":"string"===typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Za.test(a.data)&&"data");if(f||"jsonp"===a.dataTypes[0]){var g=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;f?a[f]=a[f].replace(Za,"$1"+g):!1!==a.jsonp&&(a.url+=(Xa.test(a.url)?"&":"?")+a.jsonp+"="+g);a.converters["script json"]=function(){e||
c.error(g+" was not called");return e[0]};a.dataTypes[0]="json";var h=m[g];m[g]=function(){e=arguments};d.always(function(){void 0===h?c(m).removeProp(g):m[g]=h;a[g]&&(a.jsonpCallback=b.jsonpCallback,Ob.push(g));e&&c.isFunction(h)&&h(e[0]);e=h=void 0});return"script"}});z.createHTMLDocument=function(){var a=q.implementation.createHTMLDocument("").body;a.innerHTML="<form></form><form></form>";return 2===a.childNodes.length}();c.parseHTML=function(a,b,d){if("string"!==typeof a)return[];"boolean"===
typeof b&&(d=b,b=!1);if(!b)if(z.createHTMLDocument){b=q.implementation.createHTMLDocument("");var e=b.createElement("base");e.href=q.location.href;b.head.appendChild(e)}else b=q;e=Db.exec(a);d=!d&&[];if(e)return[b.createElement(e[1])];e=db([a],b,d);d&&d.length&&c(d).remove();return c.merge([],e.childNodes)};c.fn.load=function(a,b,d){var e,f,g=this,h=a.indexOf(" ");if(-1<h){var l=c.trim(a.slice(h));a=a.slice(0,h)}c.isFunction(b)?(d=b,b=void 0):b&&"object"===typeof b&&(e="POST");0<g.length&&c.ajax({url:a,
type:e||"GET",dataType:"html",data:b}).done(function(a){f=arguments;g.html(l?c("<div>").append(c.parseHTML(a)).find(l):a)}).always(d&&function(a,b){g.each(function(){d.apply(this,f||[a.responseText,b,a])})});return this};c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(a){return this.on(b,a)}});c.expr.pseudos.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.offset={setOffset:function(a,b,d){var e=
c.css(a,"position"),f=c(a),g={};"static"===e&&(a.style.position="relative");var h=f.offset();var l=c.css(a,"top");var k=c.css(a,"left");("absolute"===e||"fixed"===e)&&-1<(l+k).indexOf("auto")?(k=f.position(),l=k.top,k=k.left):(l=parseFloat(l)||0,k=parseFloat(k)||0);c.isFunction(b)&&(b=b.call(a,d,c.extend({},h)));null!=b.top&&(g.top=b.top-h.top+l);null!=b.left&&(g.left=b.left-h.left+k);"using"in b?b.using.call(a,g):f.css(g)}};c.fn.extend({offset:function(a){if(arguments.length)return void 0===a?this:
this.each(function(b){c.offset.setOffset(this,a,b)});var b;if(b=this[0]){if(!b.getClientRects().length)return{top:0,left:0};var d=b.getBoundingClientRect();if(d.width||d.height){var e=b.ownerDocument;b=yb(e);e=e.documentElement;return{top:d.top+b.pageYOffset-e.clientTop,left:d.left+b.pageXOffset-e.clientLeft}}return d}},position:function(){if(this[0]){var a=this[0],b={top:0,left:0};if("fixed"===c.css(a,"position"))var d=a.getBoundingClientRect();else{var e=this.offsetParent();d=this.offset();c.nodeName(e[0],
"html")||(b=e.offset());b={top:b.top+c.css(e[0],"borderTopWidth",!0),left:b.left+c.css(e[0],"borderLeftWidth",!0)}}return{top:d.top-b.top-c.css(a,"marginTop",!0),left:d.left-b.left-c.css(a,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===c.css(a,"position");)a=a.offsetParent;return a||Na})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d="pageYOffset"===b;c.fn[a]=function(c){return Z(this,function(a,c,
e){var f=yb(a);if(void 0===e)return f?f[b]:a[c];f?f.scrollTo(d?f.pageXOffset:e,d?e:f.pageYOffset):a[c]=e},a,c,arguments.length)}});c.each(["top","left"],function(a,b){c.cssHooks[b]=mb(z.pixelPosition,function(a,e){if(e)return e=pa(a,b),Qa.test(e)?c(a).position()[b]+"px":e})});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,e){c.fn[e]=function(f,g){var h=arguments.length&&(d||"boolean"!==typeof f),l=d||(!0===f||!0===g?"margin":"border");
return Z(this,function(b,d,f){return c.isWindow(b)?0===e.indexOf("outer")?b["inner"+a]:b.document.documentElement["client"+a]:9===b.nodeType?(d=b.documentElement,Math.max(b.body["scroll"+a],d["scroll"+a],b.body["offset"+a],d["offset"+a],d["client"+a])):void 0===f?c.css(b,d,l):c.style(b,d,f,l)},b,h?f:void 0,h)}})});c.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,e){return this.on(b,a,c,e)},undelegate:function(a,b,
c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});c.parseJSON=JSON.parse;"function"===typeof define&&define.amd&&define("jquery",[],function(){return c});var Hc=m.jQuery,Ic=m.$;c.noConflict=function(a){m.$===c&&(m.$=Ic);a&&m.jQuery===c&&(m.jQuery=Hc);return c};p||(m.jQuery=m.$=c);return c});